/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package cheetah.digital

import cheetah.digital.verticles.BootStrapVerticle
import io.vertx.core.Vertx

class App {
    String getGreeting() {
        return 'Hello World!'
    }

    static void main(String[] args) {
        println new App().greeting
        Vertx.vertx().deployVerticle(new BootStrapVerticle())
    }
}
